import { promises as fs } from 'fs';
import { resolve, relative } from 'path';

// Vite plugin to generate a static asset manifest for Phaser autoload
export default function phaserAssetManifestPlugin({
  assetDirs = [
    'assets/autoload/drops',
    'assets/autoload/interface',
    'assets/autoload/units',
    'assets/units/avatars', // Ensure avatars are included
    'assets/locations', // Add locations for backgrounds
    'assets/units/artwork', // Add unit artwork for preloading
    // Add more asset subfolders as needed
  ],
  soundDirs = [
    'assets/sounds',
    'assets/units/sfx',
    'assets/units/shouts',
    'assets/music/epic',
    'assets/music/rock',
  ],
  locationDirs = [
    'assets/locations',
  ],
  // Directories published for `assets.getUrl()` lookups. These are NOT part of
  // the Phaser preload manifest: `getUrl` is used for cards, ability icons and
  // other UI art that is fetched on demand.
  urlDirs = [
    'assets/cards',
    'assets/icons',
    'assets/interface',
    'assets/sounds',
    'assets/stats',
    'assets/units/abilities',
    'assets/units/artwork',
    'assets/units/avatars',
  ],
  output = 'assets/index.js',
} = {}) {
  return {
    name: 'phaser-asset-manifest',
    // apply: undefined, // Run in both serve and build modes
    async buildStart() {
      const manifest = {};
      const assetPaths = {};
      for (const dir of assetDirs) {
        const absDir = resolve(process.cwd(), dir);
        try {
          const files = await getFiles(absDir);
          for (const file of files) {
            const relPath = relative(process.cwd(), file).replace(/\\/g, '/');
            manifest[relPath] = relPath;
            assetPaths[relPath] = relPath;
            // Add short key for avatars (e.g., units/avatars/Dark Priest red)
            if (/\/units\/avatars\//.test(relPath)) {
              // Match everything after 'units/avatars/' and before the extension (allow spaces, dots, etc.)
              const match = relPath.match(/units\/avatars\/([^/]+?)\.(jpg|png|jpeg)$/i);
              if (match) {
                manifest[`units/avatars/${match[1]}`] = relPath;
              }
            }
          }
        } catch (e) {}
      }
      // Gather all sound files and add short keys
      let soundPaths = [];
      for (const dir of soundDirs) {
        const absDir = resolve(process.cwd(), dir);
        try {
          const files = await getFiles(absDir);
          for (const file of files) {
            const relPath = relative(process.cwd(), file).replace(/\\/g, '/');
            if (/\.(ogg|mp3|wav)$/i.test(relPath)) {
              soundPaths.push(relPath.replace(/^assets\//, '').replace(/\.(ogg|mp3|wav)$/i, ''));
              assetPaths[relPath] = relPath;
            }
          }
        } catch (e) {}
      }
      // Register the remaining published assets so `assets.getUrl()` can resolve
      // the on-demand UI art (cards, ability icons, stat icons). These are kept
      // out of `manifest` so they are not force-preloaded into Phaser.
      for (const dir of urlDirs) {
        const absDir = resolve(process.cwd(), dir);
        try {
          const files = await getFiles(absDir);
          for (const file of files) {
            const relPath = relative(process.cwd(), file).replace(/\\/g, '/');
            assetPaths[relPath] = relPath;
          }
        } catch (e) {}
      }
      // Gather location paths (matching webpack behavior: assets/locations/*.jpg -> basename without extension)
      let locationPaths = [];
      for (const dir of locationDirs) {
        const absDir = resolve(process.cwd(), dir);
        try {
          const files = await getFiles(absDir);
          for (const file of files) {
            const relPath = relative(process.cwd(), file).replace(/\\/g, '/');
            if (/\.jpg$/i.test(relPath)) {
              const shortKey = relPath.replace(/^assets\/locations\//, '').replace(/\.jpg$/i, '');
              locationPaths.push(shortKey);
            }
          }
        } catch (e) {}
      }
      const js = `// Auto-generated by phaserAssetManifestPlugin\nexport const phaserAutoloadAssetPaths = ${JSON.stringify(manifest, null, 2)};\nexport const assetPaths = ${JSON.stringify(assetPaths, null, 2)};\nexport const soundPaths = ${JSON.stringify(soundPaths, null, 2)};\nexport const locationPaths = ${JSON.stringify(locationPaths, null, 2)};\n`;
      await fs.writeFile(resolve(process.cwd(), output), js, 'utf8');
    },
  };
}

// Recursively get all files in a directory
async function getFiles(dir) {
  let files = [];
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const res = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(await getFiles(res));
    } else {
      files.push(res);
    }
  }
  return files;
}
