/**
 * simulate.test.ts
 *
 * Single entry point for `npm run simulate`.
 *
 * Phase 1: SIM_BASELINE matches (default 20) → saves simulation-baseline.json
 * Phase 2: SIM_VARIANT matches per variant (default 10) → compares against baseline
 * Phase 3: prints improvement suggestions
 *
 * Each game takes roughly 20–40 s of wall time.
 * Default run (20 + 7×10 = 90 games) takes about 30–60 minutes.
 * For a quick smoke-test:  SIM_BASELINE=3 SIM_VARIANT=2 npm run simulate
 * For higher confidence:   SIM_BASELINE=100 SIM_VARIANT=50 npm run simulate
 *
 * Mock order matters: jest.mock() calls are hoisted before any imports.
 */

import { jest, describe, test } from '@jest/globals';
import * as fs from 'fs';
import * as path from 'path';

// ─── Mock heavy external deps BEFORE importing game modules ──────────────────

jest.mock('pixi', () => ({}), { virtual: true });
jest.mock('p2', () => ({}), { virtual: true });
jest.mock('phaser-ce', () => ({
	Point: class PointMock {},
	Polygon: class PolygonMock {},
	default: class PhaserMock {},
}));
jest.mock(
	'phaser',
	() => {
		// Minimal Phaser namespace required by game.ts / creature.ts / animations.ts
		const PhaserMock: any = {
			AUTO: 0,
			ScaleManager: { SHOW_ALL: 0 },
			Easing: {
				Linear: { None: 'Linear.None' },
				Quadratic: { In: 'Quad.In', Out: 'Quad.Out', InOut: 'Quad.InOut' },
			},
			Text: class PhaserText {},
			Sprite: class PhaserSprite {},
			Group: class PhaserGroup {},
			Tween: class PhaserTween {},
			Signal: class PhaserSignal {
				add() {}
				remove() {}
				dispatch() {}
			},
			Game: class PhaserGame {
				scale = {
					parentIsWindow: false,
					pageAlignHorizontally: false,
					pageAlignVertically: false,
					scaleMode: 0,
					fullScreenScaleMode: 0,
					refresh() {},
				};
				stage = { disableVisibilityChange: false, forcePortrait: false };
				device = { desktop: true };
				camera = { shake() {} };
				load = {
					progress: 100,
					onFileComplete: { add() {} },
					onLoadComplete: { add() {} },
					start() {},
				};
				add = {
					group: () => ({
						add: () => ({}),
						position: { set: () => {} },
						scale: { setTo: () => {}, set: () => {} },
						children: [],
						create: () => ({}),
						forEach: () => {},
						sendToBack: () => {},
						bringToTop: () => {},
						sort: () => {},
						destroy: () => {},
					}),
					sprite: () => ({
						anchor: { setTo: () => {} },
						events: { onInputUp: { add: () => {} }, onInputOver: { add: () => {} }, onInputOut: { add: () => {} } },
						inputEnabled: false,
						ignoreChildInput: false,
						input: { useHandCursor: false, priorityID: 0 },
						alpha: 1,
						exists: true,
						destroy: () => {},
					}),
					tween: (target: any) => ({
						_target: target,
						_props: null,
						to(props: any, _d: number, _e?: any, autoStart = false) {
							this._props = props;
							if (autoStart && target) Object.assign(target, props);
							return this;
						},
						start() {
							if (this._target && this._props) Object.assign(this._target, this._props);
							return this;
						},
						onComplete: { add() {}, addOnce() {} },
						onUpdateCallback() { return this; },
						stop() { return this; },
						yoyo() { return this; },
						repeat() { return this; },
					}),
					text: () => ({ anchor: { setTo: () => {} } }),
					bitmapData: () => ({ canvas: {}, context: {}, destroy: () => {} }),
				};
				world = { width: 1920, height: 1080 };
				width = 1920;
				height = 1080;
			},
		};
		PhaserMock.default = PhaserMock;
		return PhaserMock;
	},
	{ virtual: true },
);

// Mock asset path module (generated by webpack, not available in test env)
jest.mock('../../assets', () => ({
	getUrl: (p: string) => p,
	use: () => undefined,
	soundPaths: [],
}));

// Mock UI — the real UI needs a full DOM
jest.mock('../../ui/interface', () => ({
	UI: class UIStub {
		selectedAbility = -1;
		dashopen = false;
		active = false;
		_abilityPanelAnimating = false;
		chat = { hide: () => {}, addMsg: () => {} };
		updateTimer = () => {};
		checkAbilities = () => {};
		selectAbility = () => {};
		updateQueueDisplay = () => {};
		updateActivePlayerMana = () => {};
		closeDash = () => {};
		btnToggleDash = { changeState: () => {} };
		endGame = () => {};
		resizeDash = () => {};
		showCreature = () => {};
		healthBar = { animSize: () => {} };
		energyBar = { animSize: () => {} };
		xpBar = { animSize: () => {} };
		plasmaBars = [];
		materializeButton = { changeState: () => {} };
		btnDelay = { changeState: () => {} };
		btnFlee = { changeState: () => {} };
		btnSkipTurn = { changeState: () => {} };
		btnAudio = { changeState: () => {} };
	},
}));

// Mock sound system
jest.mock('../../sound/soundsys', () => ({
	SoundSys: class SoundSysStub {
		playMusic = () => {};
		stopMusic = () => {};
		playSFX = () => ({ stop: () => {} });
		playHeartBeat = () => {};
		loadSound = () => {};
		musicPlayer = { audio: { pause: () => {} } };
	},
	setAudioMode: () => {},
	getAudioMode: () => 'muted',
	cycleAudioMode: () => {},
}));

// Mock jQuery — return self-referential proxy for chainable calls;
// special-case methods that must return real values.
// NOTE: game code uses `import * as $j from 'jquery'`, so named exports matter.
jest.mock('jquery', () => {
	// jQuery.extend performs shallow/deep merge — used heavily throughout the game
	const extend = (...args: any[]) => {
		if (args.length === 0) return {};
		let idx = 0;
		if (typeof args[0] === 'boolean') idx = 1; // skip `deep` flag
		const target = args[idx] ?? {};
		for (let i = idx + 1; i < args.length; i++) {
			if (args[i] && typeof args[i] === 'object') Object.assign(target, args[i]);
		}
		return target;
	};

	const chain: any = new Proxy(
		function () {
			return chain;
		},
		{
			get(_t, p) {
				if (p === 'then' || p === Symbol.toPrimitive) return undefined;
				if (p === 'length') return 0;
				if (p === 'extend') return extend;
				if (p === 'width' || p === 'height') return () => 1920;
				if (p === 'offset') return () => ({ top: 0, left: 0 });
				return () => chain;
			},
			apply() {
				return chain;
			},
		},
	);
	// Export as a plain CJS module so babel-jest interop gives `import * as $j` = chain (callable)
	chain.default = chain;
	chain.extend = extend;
	return chain;
});

// ─── Imports (after mocks) ────────────────────────────────────────────────────

import { createGame, runMatch, SimSignal } from './botgeria';
import { aggregateMetrics, formatMetrics } from './stats';
import { variants, printReport } from './suggester';
import type { MatchResult } from './botgeria';
import type { QualityMetrics } from './stats';

// ─── Ability loaders ──────────────────────────────────────────────────────────

// Load all ability files so creatures have working skills
const ABILITY_FILES = [
	'../../abilities/Dark-Priest',
	'../../abilities/Snow-Bunny',
	'../../abilities/Abolished',
	'../../abilities/Golden-Wyrm',
	'../../abilities/Gumble',
	'../../abilities/Vehemoth',
	'../../abilities/Stomper',
	'../../abilities/Cycloper',
	'../../abilities/Impaler',
	'../../abilities/Cyber-Wolf',
];

function loadAbilities(): Array<(G: any) => void> {
	const loaders: Array<(G: any) => void> = [];
	for (const f of ABILITY_FILES) {
		try {
			// eslint-disable-next-line @typescript-eslint/no-var-requires
			const mod = require(f);
			loaders.push(mod.default ?? mod);
		} catch {
			// Ability file failed to load — game still runs without it
		}
	}
	return loaders;
}

// ─── Match batch runner ───────────────────────────────────────────────────────

async function runBatch(count: number, patchFn?: (game: any) => () => void): Promise<MatchResult[]> {
	jest.useFakeTimers();
	const abilities = loadAbilities();
	const results: MatchResult[] = [];

	for (let i = 0; i < count; i++) {
		// Clear any stale timers left over from the previous game and reset the fake
		// clock to 0.  Without this, accumulated fake time affects Date.now()-based
		// guards (stalePendingActionMs) and residual timers slow down subsequent games.
		jest.clearAllTimers();
		jest.setSystemTime(0);
		const game = createGame(abilities);
		let restore: (() => void) | undefined;
		if (patchFn) {
			restore = patchFn(game);
		}
		const result = await runMatch(game);
		restore?.();
		results.push(result);
	}

	jest.useRealTimers();
	return results;
}

// ─── The test ─────────────────────────────────────────────────────────────────

const BASELINE_PATH = path.resolve(process.cwd(), 'simulation-baseline.json');
// Default counts are intentionally small (~20–37 s per game).
// For tighter statistical confidence, increase via env vars:
//   SIM_BASELINE=100 SIM_VARIANT=50 npm run simulate
const BASELINE_COUNT = parseInt(process.env.SIM_BASELINE || '20', 10);
const VARIANT_COUNT = parseInt(process.env.SIM_VARIANT || '10', 10);

describe('Bot simulation', () => {
	test('run simulation and suggest improvements', async () => {
		// ── Phase 1: baseline ──────────────────────────────────────────────────
		console.log(`\n📊  Phase 1: running ${BASELINE_COUNT} baseline matches …`);
		const baselineResults = await runBatch(BASELINE_COUNT);
		const baselineMetrics = aggregateMetrics(baselineResults);
		console.log('Baseline: ' + formatMetrics('baseline', baselineMetrics));

		fs.writeFileSync(
			BASELINE_PATH,
			JSON.stringify({ metrics: baselineMetrics, timestamp: new Date().toISOString() }, null, 2),
		);
		console.log(`✅  Saved baseline to ${BASELINE_PATH}`);

		// ── Phase 2: variants ─────────────────────────────────────────────────
		console.log(`\n🔬  Phase 2: testing ${variants.length} variants (${VARIANT_COUNT} matches each) …`);

		const variantResults = [];
		for (const variant of variants) {
			console.log(`  Variant: ${variant.label}`);
			const matches = await runBatch(VARIANT_COUNT, variant.patch);
			const metrics = aggregateMetrics(matches);
			const isBetter = metrics.decisiveness > baselineMetrics.decisiveness * 1.05 ||
				metrics.timeoutRate < baselineMetrics.timeoutRate * 0.95;
			variantResults.push({ variant, metrics, isBetter });
		}

		// ── Phase 3: report ───────────────────────────────────────────────────
		printReport(baselineMetrics, variantResults);

		// Jest requires at least one assertion
		expect(baselineMetrics.matchCount).toBe(BASELINE_COUNT);
	});
});
